# Generated by Django 3.0.6 on 2020-05-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='price',
            new_name='quantity',
        ),
    ]
