# Generated by Django 3.0.6 on 2020-05-29 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('expired', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageFruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fruit_image/')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Fruits.Fruit')),
            ],
        ),
    ]
