# Generated by Django 3.0.6 on 2020-05-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefruit',
            name='image',
            field=models.ImageField(upload_to='media/fruit_image/'),
        ),
    ]
