# Generated by Django 3.0.6 on 2020-05-29 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('Fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(default='spending', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customers.Customer')),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='Fruits.Fruit')),
            ],
        ),
    ]
