# Generated by Django 3.0.6 on 2020-05-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200529_2352'),
        ('Fruits', '0001_initial'),
        ('orders', '0002_auto_20200529_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='own',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customers_order', to='customers.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='fruit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits_order', to='Fruits.Fruit'),
        ),
    ]
