# Generated by Django 3.0.6 on 2020-06-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0005_auto_20200604_1946'),
        ('orders', '0003_auto_20200529_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fruit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kg',
        ),
        migrations.RemoveField(
            model_name='order',
            name='own',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='spending', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='fruitOfOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruit_order', to='Fruits.Fruit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_fruit', to='orders.Order')),
            ],
        ),
    ]
